config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="mailing")),
    path("user/", include("users.urls", namespace="users")),
]

mailing/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig

from . import views

app_name = MailingConfig.name

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path(
        "recipient_list",
        cache_page(5)(views.RecipientListView.as_view()),
        name="recipient_list",
    ),
    path(
        "recipient/create", views.RecipientCreateView.as_view(), name="recipient_create"
    ),
    path(
        "recipient/<int:pk>/update",
        views.RecipientUpdateView.as_view(),
        name="recipient_update",
    ),
    path(
        "recipient/<int:pk>/delete",
        views.RecipientDeleteView.as_view(),
        name="recipient_delete",
    ),
    path(
        "message_list",
        cache_page(5)(views.MessageListView.as_view()),
        name="message_list",
    ),
    path("message/create", views.MessageCreateView.as_view(), name="message_create"),
    path(
        "message/<int:pk>/update",
        views.MessageUpdateView.as_view(),
        name="message_update",
    ),
    path(
        "message/<int:pk>/delete",
        views.MessageDeleteView.as_view(),
        name="message_delete",
    ),
    path(
        "mailing_list",
        cache_page(5)(views.MailingListView.as_view()),
        name="mailing_list",
    ),
    path("mailing/create", views.MailingCreateView.as_view(), name="mailing_create"),
    path(
        "mailing/<int:pk>/update",
        views.MailingUpdateView.as_view(),
        name="mailing_update",
    ),
    path(
        "mailing/<int:pk>/stop",
        views.MailingStopView.as_view(),
        name="mailing_stop",
    ),
    path(
        "mailing/<int:pk>/delete",
        views.MailingDeleteView.as_view(),
        name="mailing_delete",
    ),
    path("mailing/<int:pk>", views.MailingDetailView.as_view(), name="mailing_detail"),
    path(
        "mailingattempt_list",
        cache_page(5)(views.MailingAttemptListView.as_view()),
        name="mailingattempt_list",
    ),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from users.apps import UsersConfig

from . import views

app_name = UsersConfig.name

urlpatterns = [
    path("users/", views.UserListView.as_view(), name="users"),
    path("users/<int:pk>/block", views.UserBlockView.as_view(), name="user_block"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path(
        "logout/",
        auth_views.LogoutView.as_view(next_page="mailing:index"),
        name="logout",
    ),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("email-confirm/<str:token>/", views.email_verification, name="email-confirm"),
    # Страница для ввода email
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="password_reset/password_reset_form.html",
            email_template_name="password_reset/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    # Уведомление об отправке email
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="password_reset/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    # Ссылка из email, форма ввода нового пароля
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    # Уведомление об успешном сбросе пароля
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="password_reset/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/forms.py
from django import forms

from .models import Mailing, Message, Recipient


class MailingForm(forms.ModelForm):
    class Meta:
        model = Mailing
        fields = "__all__"
        exclude = [
            "owner",
        ]
        widgets = {
            "recipients": forms.CheckboxSelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)  # Получаем текущего пользователя
        super().__init__(*args, **kwargs)

        if user:
            # Фильтруем только те recipients, которые принадлежат текущему пользователю
            self.fields["recipients"].queryset = Recipient.objects.filter(owner=user)
            self.fields["message"].queryset = Message.objects.filter(owner=user)


class RecipientForm(forms.ModelForm):

    class Meta:
        # Название модели на основе
        # которой создается форма
        model = Recipient
        # Включаем все поля с модели в форму
        fields = "__all__"
        exclude = [
            "owner",
        ]


class MessageForm(forms.ModelForm):

    class Meta:
        # Название модели на основе
        # которой создается форма
        model = Message
        # Включаем все поля с модели в форму
        fields = "__all__"
        exclude = [
            "owner",
        ]

mailing/views.py
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import DetailView, ListView, TemplateView, View
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from mailing.forms import MailingForm, MessageForm, RecipientForm
from mailing.models import Mailing, MailingAttempt, Message, Recipient
from mailing.services import get_index_page_cache_data


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = "mailing/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # получаем текущего пользователя и идем в кеш
        user = self.request.user
        context.update(get_index_page_cache_data(user))

        return context


# CRUD для модели "Получатель рассылки"
class RecipientListView(LoginRequiredMixin, ListView):
    model = Recipient

    def get_queryset(self):
        # фильтр данных по пользователю
        user = self.request.user
        if user.groups.filter(name="Менеджер").exists():
            return Recipient.objects.all()
        return Recipient.objects.filter(owner=user.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Проверка, состоит ли пользователь в группе "Менеджер"
        is_manager = self.request.user.groups.filter(name="Менеджер").exists()

        # Добавляем в контекст информацию, что пользователь является модератором
        context["is_manager"] = is_manager
        return context


class RecipientCreateView(LoginRequiredMixin, CreateView):
    model = Recipient
    form_class = RecipientForm
    success_url = reverse_lazy("mailing:recipient_list")

    def form_valid(self, form):
        recipient = form.save()
        user = self.request.user
        recipient.owner = user
        recipient.save()
        return super().form_valid(form)


class RecipientUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipient
    form_class = RecipientForm
    success_url = reverse_lazy("mailing:recipient_list")

    def dispatch(self, request, *args, **kwargs):
        # Получаем объект
        obj = super().get_object()
        # Проверяем, является ли текущий пользователь владельцем объекта
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden(
            "Вы не можете просматривать/изменять/удалять этот объект."
        )


class RecipientDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipient
    success_url = reverse_lazy("mailing:recipient_list")

    def dispatch(self, request, *args, **kwargs):
        # Получаем объект
        obj = super().get_object()
        # Проверяем, является ли текущий пользователь владельцем объекта
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden(
            "Вы не можете просматривать/изменять/удалять этот объект."
        )


# CRUD для модели "Сообщение"
class MessageListView(LoginRequiredMixin, ListView):
    model = Message

    def get_queryset(self):
        # фильтр данных по пользователю
        user = self.request.user
        if user.groups.filter(name="Менеджер").exists():
            return Message.objects.all()
        return Message.objects.filter(owner=user.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Проверка, состоит ли пользователь в группе "Менеджер"
        is_manager = self.request.user.groups.filter(name="Менеджер").exists()

        # Добавляем в контекст информацию, что пользователь является модератором
        context["is_manager"] = is_manager
        return context


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("mailing:message_list")

    def form_valid(self, form):
        message = form.save()
        user = self.request.user
        message.owner = user
        message.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("mailing:message_list")

    def dispatch(self, request, *args, **kwargs):
        # Получаем объект
        obj = super().get_object()
        # Проверяем, является ли текущий пользователь владельцем объекта
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden(
            "Вы не можете просматривать/изменять/удалять этот объект."
        )


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy("mailing:message_list")

    def dispatch(self, request, *args, **kwargs):
        # Получаем объект
        obj = super().get_object()
        # Проверяем, является ли текущий пользователь владельцем объекта
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden(
            "Вы не можете просматривать/изменять/удалять этот объект."
        )


# CRUD для модели "Рассылки"
class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing

    def get_queryset(self):

        # фильтр данных по пользователю
        user = self.request.user
        if user.groups.filter(name="Менеджер").exists():
            return Mailing.objects.prefetch_related("recipients")
        return Mailing.objects.filter(owner=user.id).prefetch_related("recipients")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Проверка, состоит ли пользователь в группе "Менеджер"
        is_manager = self.request.user.groups.filter(name="Менеджер").exists()

        # Добавляем в контекст информацию, что пользователь является модератором
        context["is_manager"] = is_manager
        return context


class MailingStopView(LoginRequiredMixin, View):
    def post(self, request, pk):
        mailing = get_object_or_404(Mailing, pk=pk)
        user = request.user

        # Проверка, состоит ли пользователь в группе "Менеджер"
        is_manager = user.groups.filter(name="Менеджер").exists()

        if is_manager or user == mailing.owner:
            # Логика снятия с публикации
            mailing.status = "completed"
            mailing.save()

            return redirect("mailing:mailing_list")
        return HttpResponseForbidden("У вас нет прав для отключения рассылки")


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy("mailing:mailing_list")

    def form_valid(self, form):
        mailing = form.save()
        user = self.request.user
        mailing.owner = user
        mailing.save()
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user  # Передаем текущего пользователя
        return kwargs


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy("mailing:mailing_list")

    def dispatch(self, request, *args, **kwargs):
        # Получаем объект
        obj = super().get_object()
        # Проверяем, является ли текущий пользователь владельцем объекта
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden(
            "Вы не можете просматривать/изменять/удалять этот объект."
        )


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy("mailing:mailing_list")

    def dispatch(self, request, *args, **kwargs):
        # Получаем объект
        obj = super().get_object()
        # Проверяем, является ли текущий пользователь владельцем объекта
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden(
            "Вы не можете просматривать/изменять/удалять этот объект."
        )


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing

    def get_queryset(self):
        queryset = Mailing.objects.prefetch_related("recipients")
        return queryset

    def dispatch(self, request, *args, **kwargs):
        # Получаем объект
        obj = super().get_object()
        # Проверяем, является ли текущий пользователь владельцем объекта
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden(
            "Вы не можете просматривать/изменять/удалять этот объект."
        )

    def post(self, request, *args, **kwargs):

        self.object = self.get_object()
        # Получите данные, которые хотите отправить
        subject = self.object.message
        message = self.object.message.message
        # self.object.status = "running"
        # self.object.save()
        from_email = "barchatovkirill@mail.ru"
        recipient_list = [
            recipient.email for recipient in self.object.recipients.all()
        ]  # Укажите адреса получателей

        # Отправка письма
        # responses = {}

        for recipient in recipient_list:
            try:
                send_mail(subject, message, from_email, [recipient])
                response = f"{recipient}: Успешно отправлено"
                MailingAttempt.objects.create(
                    attempted_at=timezone.now(),
                    status="success",

mailing/templates/mailing/base.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <script src="/static/js/color-modes.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>{% block title %}Сервис управления рассылками{% endblock %}</title>

<!--    Ссылка на каноничный исходник - не знаю зачем надо-->
<!--    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/dashboard/">-->

<!--    Стилизация поиска - не знаю зачем, может для мобильной версии?-->
<!--    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">-->

    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/styles.css">

    <!-- Custom styles for this template -->
<!--    Иконки бутстрапа - не знаю зачем-->
<!--    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.min.css" rel="stylesheet">-->
    <!-- Custom styles for this template -->

    <link href="/static/css/dashboard.css" rel="stylesheet">


</head>

<body>

{% include 'mailing/includes/light_mode_menu.html' %}

{% include 'mailing/includes/header.html' %}



<div class="container-fluid">
    <div class="row">
        {% include 'mailing/includes/menu.html' %}

        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">

            {% block content %}{% endblock %}

            {% block content_2 %}{% endblock %}

        </main>
    </div>
</div>
<script src="/static/js/bootstrap.bundle.min.js"></script>


</body>
</html>

mailing/templates/mailing/index.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="container-fluid text-center">
    <div class="row mt-3">

        <div class="col-3 d-flex">
            <div class="card flex-fill">
                <h5 class="card-header">Всего рассылок</h5>
                <div class="card-body">
                    <h1 class="card-title">{{ mailing_count }}</h1>
                </div>
            </div>
        </div>


        <div class="col-3 d-flex">
            <div class="card flex-fill">
                <h5 class="card-header">Всего активных рассылок</h5>
                <div class="card-body">
                    <h1 class="card-title">{{ mailing_running_count }}</h1>
                </div>
            </div>
        </div>

        <div class="col-3 d-flex">
            <div class="card flex-fill">
                <h5 class="card-header">Всего попыток отправки</h5>
                <div class="card-body">
                    <h1 class="card-title">{{ attempt_count }}</h1>
                </div>
            </div>
        </div>

        <div class="col-3 d-flex">
            <div class="card flex-fill">
                <h5 class="card-header">Количество получателей</h5>
                <div class="card-body">
                    <h1 class="card-title">{{ recipient_count }}</h1>
                </div>
            </div>
        </div>

    </div>
</div>

{% include 'mailing/includes/dashboard.html' %}

{% endblock %}

{% block content_2 %}

{% include 'mailing/list.html' %}

{% endblock %}

mailing/templates/mailing/list.html
<h2>Попытки рассылки</h2>

<div class="table-responsive small">
    <table class="table table-striped table-sm">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col" >Дата и время попытки отправки</th>
            <th scope="col">Статус</th>
            <th scope="col">Ответ почтового сервера</th>
            <th scope="col">Рассылка</th>
        </tr>
        </thead>
        <tbody>
        {% for attempt in object_list %}
        <tr>
            <td>{{ attempt.id }}</td>
            <td>{{ attempt.attempted_at }}</td>
            <td>{{ attempt.status }}</td>
            <td>{{ attempt.mail_server_response }}</td>
            <td>{{ attempt.mailing }}</td>

        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block title %}Управление рассылками{% endblock %}

{% block content %}

<h2>Вы действительно хотите удалить рассылку?</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="table-responsive small">
        <table class="table table-striped table-sm">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Дата и время первой отправки</th>
                <th scope="col">Дата и время окончания отправки</th>
                <th scope="col">Статус</th>
                <th scope="col">Сообщение</th>
                <th scope="col">Получатели</th>
            </tr>
            </thead>
            <tbody>

            <tr>
                <td>{{ object.id }}</td>
                <td>{{ object.first_send_at }}</td>
                <td>{{ object.finish_send_at }}</td>
                <td>{{ object.status }}</td>
                <td>{{ object.message }}</td>
                <td>{{ object.recipients }}</td>
                <td class="text-end">
                    <button type="submit" class="btn btn-lg btn-block btn-outline-danger">Подтвердить</button>
                    <a class="btn btn-outline-primary" href="{% url 'mailing:mailing_list' %}">Отменить</a>
                </td>
            </tr>

            </tbody>
        </table>
    </div>
</form>

{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/base.html' %}

{% block title %}Управление рассылками{% endblock %}

{% block content %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h2>Подтверждение выполнения рассылки</h2>
    <div class="btn-toolbar mb-2 mb-md-0">
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-primary m-1">Подтвердить выполнение
                рассылки
            </button>
        </form>

        <a class="btn btn-outline-primary m-1" href="{% url 'mailing:mailing_update' object.pk%}">Изменить</a>
        <a class="btn btn-outline-danger m-1" href="{% url 'mailing:mailing_delete' object.pk%}">Удалить</a>
    </div>
</div>


<div class="container text-start">
    <div class="row align-items-start">

        <div class="col-4">
            <div class="row">
                <div class="col-12">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <h6 class="card-subtitle mb-2 text-body-secondary">Тема</h6>
                            <h5 class="card-title">{{ object.message }}</h5>

                        </div>
                    </div>
                </div>
            </div>


            <div class="row">
                <div class="col-12">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <h6 class="card-subtitle mb-2 text-body-secondary">Сообщение</h6>
                            {{ object.message.message }}
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="col-4 d-flex">
            <div class="card mb-4 box-shadow w-100">
                <div class="card-header">
                    Получатели
                </div>
                <ul class="list-group list-group-flush">
                    {% for recipient in object.recipients.all %}
                    <li class="list-group-item">{{ recipient.email }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="col-4 d-flex">
            <div class="card mb-4 box-shadow w-100">
                <div class="card-body">
                    <h5 class="card-title">Параметры рассылки</h5>
                    <h6 class="card-subtitle mb-2 text-body-secondary">Дата и время первой отправки</h6>
                    <p class="card-text">{{ object.first_send_at }}</p>
                    <h6 class="card-subtitle mb-2 text-body-secondary">Дата и время окончания отправки</h6>
                    <p class="card-text">{{ object.finish_send_at }}</p>
                    <h6 class="card-subtitle mb-2 text-body-secondary">Статус</h6>
                    <p class="card-text">{{ object.status }}</p>

                </div>
            </div>
        </div>

    </div>
</div>


{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html' %}

{% block title %}Управление рассылками{% endblock %}

{% block content %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h2>Управление рассылками</h2>
    <div class="btn-toolbar mb-2 mb-md-0">
        <a class="btn btn-outline-primary" href="{% url 'mailing:mailing_create' %}">Добавить</a>
    </div>
</div>


<div class="table-responsive small">
    <table class="table table-striped table-sm">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Дата и время первой отправки</th>
            <th scope="col">Дата и время окончания отправки</th>
            <th scope="col">Статус автоматической рассылки</th>
            <th scope="col">Сообщение</th>
            <th scope="col">Получатели</th>
        </tr>
        </thead>
        <tbody>
        {% for mailing in object_list %}
        <tr>
            <td>{{ mailing.id }}</td>
            <td>{{ mailing.first_send_at }}</td>
            <td>{{ mailing.finish_send_at }}</td>
            <td>{{ mailing.status }}
            {% if mailing.owner == user or is_manager %}
                {% if mailing.status != "completed" %}
                <form action="{% url 'mailing:mailing_stop' mailing.pk %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-danger btn-sm">Завершить/отключить</button>
                </form>
                {% endif %}
                {% endif %}
            </td>
            <td>{{ mailing.message }}</td>
            <td>

                {% for recipient in mailing.recipients.all %}
                {{ recipient.email }}<br>
                {% endfor %}


            </td>

            <td class="text-end">
                {% if mailing.owner == user %}

                <a class="btn btn-outline-primary" href="{% url 'mailing:mailing_detail' mailing.pk%}">Разослать вручную</a>

                <a class="btn btn-outline-primary" href="{% url 'mailing:mailing_update' mailing.pk%}">Изменить</a>
                <a class="btn btn-outline-danger" href="{% url 'mailing:mailing_delete' mailing.pk%}">Удалить</a>
                {% endif %}
            </td>

        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

mailing/templates/mailing/message_list.html
{% extends 'mailing/base.html' %}

{% block title %}Рассылаемые сообщения{% endblock %}

{% block content %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h2>Рассылаемые сообщения</h2>
    <div class="btn-toolbar mb-2 mb-md-0">
        <a class="btn btn-outline-primary" href="{% url 'mailing:message_create' %}">Добавить</a>
    </div>
</div>


<div class="table-responsive small">
    <table class="table table-striped table-sm">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col" >Тема письма</th>
            <th scope="col">Тело письма</th>
        </tr>
        </thead>
        <tbody>
        {% for message in object_list %}
        <tr>
            <td>{{ message.id }}</td>
            <td style="width: 20vh;">{{ message.title }}</td>
            <td>{{ message.message }}</td>
            {% if message.owner == user %}
            <td class="text-end" style="width: 20vh;">
                <a class="btn btn-outline-primary" href="{% url 'mailing:message_update' message.pk%}">Изменить</a>
                <a class="btn btn-outline-danger" href="{% url 'mailing:message_delete' message.pk%}">Удалить</a>
            </td>
            {% else %}
            <td class="text-end" style="width: 20vh;"></td>
            {% endif %}
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

mailing/templates/mailing/recipient_list.html
{% extends 'mailing/base.html' %}

{% block title %}Получатели рассылки{% endblock %}

{% block content %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h2>Получатели рассылки</h2>
    <div class="btn-toolbar mb-2 mb-md-0">
        <a class="btn btn-outline-primary" href="{% url 'mailing:recipient_create' %}">Добавить</a>
    </div>
</div>


<div class="table-responsive small">
    <table class="table table-striped table-sm">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Почта</th>
            <th scope="col">ФИО</th>
            <th scope="col">Комментарий</th>
        </tr>
        </thead>
        <tbody>
        {% for recipient in object_list %}
        <tr>
            <td>{{ recipient.id }}</td>
            <td>{{ recipient.email }}</td>
            <td>{{ recipient.full_name }}</td>
            <td>{{ recipient.comment }}</td>
            {% if recipient.owner == user %}
            <td class="text-end" style="width: 20vh;">
                <a class="btn btn-outline-primary" href="{% url 'mailing:recipient_update' recipient.pk%}">Изменить</a>
                <a class="btn btn-outline-danger" href="{% url 'mailing:recipient_delete' recipient.pk%}">Удалить</a>
            </td>
            {% else %}
            <td class="text-end" style="width: 20vh;"></td>
            {% endif %}
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}