config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="mailing")),
    path("user/", include("users.urls", namespace="users")),
]

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from users.apps import UsersConfig

from . import views

app_name = UsersConfig.name

urlpatterns = [
    path("users/", views.UserListView.as_view(), name="users"),
    path("users/<int:pk>/block", views.UserBlockView.as_view(), name="user_block"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path(
        "logout/",
        auth_views.LogoutView.as_view(next_page="mailing:index"),
        name="logout",
    ),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("email-confirm/<str:token>/", views.email_verification, name="email-confirm"),
    # Страница для ввода email
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="password_reset/password_reset_form.html",
            email_template_name="password_reset/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    # Уведомление об отправке email
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="password_reset/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    # Ссылка из email, форма ввода нового пароля
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    # Уведомление об успешном сбросе пароля
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="password_reset/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    """Кастомная модель пользователя"""

    # юзернейм не используется
    username = None

    email = models.EmailField(unique=True, verbose_name="Электронная почта")
    password = models.CharField(max_length=128, verbose_name="Пароль")

    # токен для подтверждения почты
    token = models.CharField(
        max_length=100, blank=True, null=True, verbose_name="Токен"
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        permissions = [
            ("can_block_user", "Can block user"),
        ]

users/forms.py
from django.contrib.auth.forms import UserCreationForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    """Форма для создания пользователя"""

    class Meta:
        model = CustomUser
        fields = ("email", "password1", "password2")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Для перевода на русский
        self.fields["password1"].label = "Ваш пароль"  # Меняем label для password1
        self.fields["password2"].label = (
            "Повторите пароль"  # Меняем label для password2
        )

        self.fields["password1"].help_text = (
            "- Ваш пароль не должен быть слишком похож на другую личную информацию.<br>"
            "- Ваш пароль должен содержать как минимум 8 символов.<br>"
            "- Ваш пароль не должен быть распространённым.<br>"
            "- Ваш пароль не должен состоять только из цифр."
        )

        self.fields["password2"].help_text = "Введите тот же пароль для подтверждения."

users/views.py
import secrets

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, View
from django.views.generic.edit import CreateView

from config.settings import DEFAULT_FROM_EMAIL

from .forms import CustomUserCreationForm
from .models import CustomUser


# Контроллер для модели "Пользователь"
class UserListView(LoginRequiredMixin, ListView):
    model = CustomUser

    def dispatch(self, request, *args, **kwargs):
        # проверяем права
        user = self.request.user
        if user.groups.filter(name="Менеджер").exists():
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden(
            "Вы не можете просматривать/изменять/удалять этот объект."
        )


class UserBlockView(LoginRequiredMixin, View):
    def post(self, request, pk):
        system_user = get_object_or_404(CustomUser, pk=pk)

        if not request.user.has_perm("users.can_block_user"):
            return HttpResponseForbidden("У вас нет прав для блокировки пользователя")

        # Логика блокировки
        system_user.is_active = not system_user.is_active
        system_user.save()

        return redirect("users:users")


class RegisterView(CreateView):
    form_class = CustomUserCreationForm
    template_name = "registration/register.html"
    success_url = reverse_lazy("mailing:index")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f"http://{host}/user/email-confirm/{token}/"
        send_mail(
            subject="Подтверждение почты",
            message=f"Приветствуем тебя на нашем сайте! Перейди, пожалуйста, по ссылке для подтверждения почты {url}",
            from_email=DEFAULT_FROM_EMAIL,
            recipient_list=[user.email],
        )
        return super().form_valid(form)


def email_verification(request, token):
    """Логика подтверждения почты"""

    user = get_object_or_404(CustomUser, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse("user:login"))

users/templates/password_reset/password_reset_complete.html
<!-- registration/password_reset_complete.html -->
{% extends "mailing/base.html" %}
{% block title %}Пароль успешно сброшен{% endblock %}

{% block content %}
<div class="container">
    <div class="row d-flex justify-content-center text-start">
        <div class="col-lg-6 col-md-8 col-sm-10">
            <div class="card mt-4 mb-4 shadow-sm">
                <div class="card-body text-center">
                    <h2 class="mb-4">Пароль успешно сброшен</h2>
                    <p>Теперь вы можете <a href="{% url 'users:login' %}">войти</a> с новым паролем.</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/password_reset/password_reset_confirm.html
<!-- registration/password_reset_confirm.html -->
{% extends "mailing/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Сброс пароля{% endblock %}

{% block content %}
<div class="container">
    <div class="row d-flex justify-content-center text-start">
        <div class="col-lg-6 col-md-8 col-sm-10">
            <div class="card mt-4 mb-4 shadow-sm">
                <div class="card-body">
                    <h2 class="text-center mb-4">Установите новый пароль</h2>
                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-primary w-100">Сбросить пароль</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/password_reset/password_reset_done.html
<!-- registration/password_reset_done.html -->
{% extends "mailing/base.html" %}
{% block title %}Письмо отправлено{% endblock %}

{% block content %}
<div class="container">
    <div class="row d-flex justify-content-center text-start">
        <div class="col-lg-6 col-md-8 col-sm-10">
            <div class="card mt-4 mb-4 shadow-sm">
                <div class="card-body text-center">
                    <h2 class="mb-4">Письмо отправлено</h2>
                    <p>Проверьте вашу почту для получения ссылки на восстановление пароля.</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/password_reset/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/password_reset/password_reset_form.html
<!-- registration/password_reset_form.html -->
{% extends "mailing/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Восстановление пароля{% endblock %}

{% block content %}
<div class="container">
    <div class="row d-flex justify-content-center text-start">
        <div class="col-lg-6 col-md-8 col-sm-10">
            <div class="card mt-4 mb-4 shadow-sm">
                <div class="card-body">
                    <h2 class="text-center mb-4">Восстановление пароля</h2>
                    <p class="text-center">Введите ваш email, и мы отправим вам ссылку для сброса пароля.</p>
                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-primary w-100">Сбросить пароль</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}