config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="mailing")),
    path("user/", include("users.urls", namespace="users")),
]

mailing/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig

from . import views

app_name = MailingConfig.name

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path(
        "recipient_list",
        cache_page(5)(views.RecipientListView.as_view()),
        name="recipient_list",
    ),
    path(
        "recipient/create", views.RecipientCreateView.as_view(), name="recipient_create"
    ),
    path(
        "recipient/<int:pk>/update",
        views.RecipientUpdateView.as_view(),
        name="recipient_update",
    ),
    path(
        "recipient/<int:pk>/delete",
        views.RecipientDeleteView.as_view(),
        name="recipient_delete",
    ),
    path(
        "message_list",
        cache_page(5)(views.MessageListView.as_view()),
        name="message_list",
    ),
    path("message/create", views.MessageCreateView.as_view(), name="message_create"),
    path(
        "message/<int:pk>/update",
        views.MessageUpdateView.as_view(),
        name="message_update",
    ),
    path(
        "message/<int:pk>/delete",
        views.MessageDeleteView.as_view(),
        name="message_delete",
    ),
    path(
        "mailing_list",
        cache_page(5)(views.MailingListView.as_view()),
        name="mailing_list",
    ),
    path("mailing/create", views.MailingCreateView.as_view(), name="mailing_create"),
    path(
        "mailing/<int:pk>/update",
        views.MailingUpdateView.as_view(),
        name="mailing_update",
    ),
    path(
        "mailing/<int:pk>/stop",
        views.MailingStopView.as_view(),
        name="mailing_stop",
    ),
    path(
        "mailing/<int:pk>/delete",
        views.MailingDeleteView.as_view(),
        name="mailing_delete",
    ),
    path("mailing/<int:pk>", views.MailingDetailView.as_view(), name="mailing_detail"),
    path(
        "mailingattempt_list",
        cache_page(5)(views.MailingAttemptListView.as_view()),
        name="mailingattempt_list",
    ),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from users.apps import UsersConfig

from . import views

app_name = UsersConfig.name

urlpatterns = [
    path("users/", views.UserListView.as_view(), name="users"),
    path("users/<int:pk>/block", views.UserBlockView.as_view(), name="user_block"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path(
        "logout/",
        auth_views.LogoutView.as_view(next_page="mailing:index"),
        name="logout",
    ),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("email-confirm/<str:token>/", views.email_verification, name="email-confirm"),
    # Страница для ввода email
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="password_reset/password_reset_form.html",
            email_template_name="password_reset/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    # Уведомление об отправке email
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="password_reset/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    # Ссылка из email, форма ввода нового пароля
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    # Уведомление об успешном сбросе пароля
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="password_reset/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/forms.py
from django import forms

from .models import Mailing, Message, Recipient


class MailingForm(forms.ModelForm):
    class Meta:
        model = Mailing
        fields = "__all__"
        exclude = [
            "owner",
        ]
        widgets = {
            "recipients": forms.CheckboxSelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)  # Получаем текущего пользователя
        super().__init__(*args, **kwargs)

        if user:
            # Фильтруем только те recipients, которые принадлежат текущему пользователю
            self.fields["recipients"].queryset = Recipient.objects.filter(owner=user)
            self.fields["message"].queryset = Message.objects.filter(owner=user)


class RecipientForm(forms.ModelForm):

    class Meta:
        # Название модели на основе
        # которой создается форма
        model = Recipient
        # Включаем все поля с модели в форму
        fields = "__all__"
        exclude = [
            "owner",
        ]


class MessageForm(forms.ModelForm):

    class Meta:
        # Название модели на основе
        # которой создается форма
        model = Message
        # Включаем все поля с модели в форму
        fields = "__all__"
        exclude = [
            "owner",
        ]

mailing/views.py
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import DetailView, ListView, TemplateView, View
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from mailing.forms import MailingForm, MessageForm, RecipientForm
from mailing.models import Mailing, MailingAttempt, Message, Recipient
from mailing.services import get_index_page_cache_data


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = "mailing/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # получаем текущего пользователя и идем в кеш
        user = self.request.user
        context.update(get_index_page_cache_data(user))

        return context


# CRUD для модели "Получатель рассылки"
class RecipientListView(LoginRequiredMixin, ListView):
    model = Recipient

    def get_queryset(self):
        # фильтр данных по пользователю
        user = self.request.user
        if user.groups.filter(name="Менеджер").exists():
            return Recipient.objects.all()
        return Recipient.objects.filter(owner=user.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Проверка, состоит ли пользователь в группе "Менеджер"
        is_manager = self.request.user.groups.filter(name="Менеджер").exists()

        # Добавляем в контекст информацию, что пользователь является модератором
        context["is_manager"] = is_manager
        return context


class RecipientCreateView(LoginRequiredMixin, CreateView):
    model = Recipient
    form_class = RecipientForm
    success_url = reverse_lazy("mailing:recipient_list")

    def form_valid(self, form):
        recipient = form.save()
        user = self.request.user
        recipient.owner = user
        recipient.save()
        return super().form_valid(form)


class RecipientUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipient
    form_class = RecipientForm
    success_url = reverse_lazy("mailing:recipient_list")

    def dispatch(self, request, *args, **kwargs):
        # Получаем объект
        obj = super().get_object()
        # Проверяем, является ли текущий пользователь владельцем объекта
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden(
            "Вы не можете просматривать/изменять/удалять этот объект."
        )


class RecipientDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipient
    success_url = reverse_lazy("mailing:recipient_list")

    def dispatch(self, request, *args, **kwargs):
        # Получаем объект
        obj = super().get_object()
        # Проверяем, является ли текущий пользователь владельцем объекта
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden(
            "Вы не можете просматривать/изменять/удалять этот объект."
        )


# CRUD для модели "Сообщение"
class MessageListView(LoginRequiredMixin, ListView):
    model = Message

    def get_queryset(self):
        # фильтр данных по пользователю
        user = self.request.user
        if user.groups.filter(name="Менеджер").exists():
            return Message.objects.all()
        return Message.objects.filter(owner=user.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Проверка, состоит ли пользователь в группе "Менеджер"
        is_manager = self.request.user.groups.filter(name="Менеджер").exists()

        # Добавляем в контекст информацию, что пользователь является модератором
        context["is_manager"] = is_manager
        return context


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("mailing:message_list")

    def form_valid(self, form):
        message = form.save()
        user = self.request.user
        message.owner = user
        message.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("mailing:message_list")

    def dispatch(self, request, *args, **kwargs):
        # Получаем объект
        obj = super().get_object()
        # Проверяем, является ли текущий пользователь владельцем объекта
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden(
            "Вы не можете просматривать/изменять/удалять этот объект."
        )


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy("mailing:message_list")

    def dispatch(self, request, *args, **kwargs):
        # Получаем объект
        obj = super().get_object()
        # Проверяем, является ли текущий пользователь владельцем объекта
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden(
            "Вы не можете просматривать/изменять/удалять этот объект."
        )


# CRUD для модели "Рассылки"
class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing

    def get_queryset(self):

        # фильтр данных по пользователю
        user = self.request.user
        if user.groups.filter(name="Менеджер").exists():
            return Mailing.objects.prefetch_related("recipients")
        return Mailing.objects.filter(owner=user.id).prefetch_related("recipients")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Проверка, состоит ли пользователь в группе "Менеджер"
        is_manager = self.request.user.groups.filter(name="Менеджер").exists()

        # Добавляем в контекст информацию, что пользователь является модератором
        context["is_manager"] = is_manager
        return context


class MailingStopView(LoginRequiredMixin, View):
    def post(self, request, pk):
        mailing = get_object_or_404(Mailing, pk=pk)
        user = request.user

        # Проверка, состоит ли пользователь в группе "Менеджер"
        is_manager = user.groups.filter(name="Менеджер").exists()

        if is_manager or user == mailing.owner:
            # Логика снятия с публикации
            mailing.status = "completed"
            mailing.save()

            return redirect("mailing:mailing_list")
        return HttpResponseForbidden("У вас нет прав для отключения рассылки")


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy("mailing:mailing_list")

    def form_valid(self, form):
        mailing = form.save()
        user = self.request.user
        mailing.owner = user
        mailing.save()
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user  # Передаем текущего пользователя
        return kwargs


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy("mailing:mailing_list")

    def dispatch(self, request, *args, **kwargs):
        # Получаем объект
        obj = super().get_object()
        # Проверяем, является ли текущий пользователь владельцем объекта
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden(
            "Вы не можете просматривать/изменять/удалять этот объект."
        )


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy("mailing:mailing_list")

    def dispatch(self, request, *args, **kwargs):
        # Получаем объект
        obj = super().get_object()
        # Проверяем, является ли текущий пользователь владельцем объекта
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden(
            "Вы не можете просматривать/изменять/удалять этот объект."
        )


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing

    def get_queryset(self):
        queryset = Mailing.objects.prefetch_related("recipients")
        return queryset

    def dispatch(self, request, *args, **kwargs):
        # Получаем объект
        obj = super().get_object()
        # Проверяем, является ли текущий пользователь владельцем объекта
        if obj.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        return HttpResponseForbidden(
            "Вы не можете просматривать/изменять/удалять этот объект."
        )

    def post(self, request, *args, **kwargs):

        self.object = self.get_object()
        # Получите данные, которые хотите отправить
        subject = self.object.message
        message = self.object.message.message
        # self.object.status = "running"
        # self.object.save()
        from_email = "barchatovkirill@mail.ru"
        recipient_list = [
            recipient.email for recipient in self.object.recipients.all()
        ]  # Укажите адреса получателей

        # Отправка письма
        # responses = {}

        for recipient in recipient_list:
            try:
                send_mail(subject, message, from_email, [recipient])
                response = f"{recipient}: Успешно отправлено"
                MailingAttempt.objects.create(
                    attempted_at=timezone.now(),
                    status="success",

mailing/templates/mailing/includes/dashboard.html
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Попытки рассылки</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group me-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
        </div>
        <button type="button"
                class="btn btn-sm btn-outline-secondary dropdown-toggle d-flex align-items-center gap-1">
            <svg class="bi">
                <use xlink:href="/static/svg/icons-menu.svg#calendar3"/>
            </svg>
            This week
        </button>
    </div>
</div>

<canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>

<div id="chart-data"
     data-success="{{ attempt_success_count }}"
     data-failure="{{ attempt_failure_count }}">
</div>

<script src="/static/js/chart.umd.js"></script>
<script src="/static/js/dashboard_mailing_attempt.js"></script>

mailing/templates/mailing/includes/header.html
<header class="navbar sticky-top bg-dark flex-md-nowrap p-0 shadow" data-bs-theme="dark">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6 text-white" href="#">Сервис управления рассылками</a>

    <div class="navbar-nav text-white me-5">
        {{ user.email }}
    </div>

    <!--    Адаптив для мобильных устройств-->
    <ul class="navbar-nav flex-row d-md-none">
        <li class="nav-item text-nowrap">
            <button class="nav-link px-3 text-white" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSearch" aria-controls="navbarSearch" aria-expanded="false"
                    aria-label="Toggle search">
                <svg class="bi">
                    <use xlink:href="/static/svg/icons-menu.svg#search"/>
                </svg>
            </button>
        </li>
        <li class="nav-item text-nowrap">
            <button class="nav-link px-3 text-white" type="button" data-bs-toggle="offcanvas"
                    data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false"
                    aria-label="Toggle navigation">
                <svg class="bi">
                    <use xlink:href="/static/svg/icons-menu.svg#list"/>
                </svg>
            </button>
        </li>
    </ul>

    <div id="navbarSearch" class="navbar-search w-100 collapse">
        <input class="form-control w-100 rounded-0 border-0" type="text" placeholder="Search" aria-label="Search">
    </div>
</header>

mailing/templates/mailing/includes/light_mode_menu.html
<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="/static/svg/icons-light-mode.svg#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="/static/svg/icons-light-mode.svg#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="/static/svg/icons-light-mode.svg#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="/static/svg/icons-light-mode.svg#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="/static/svg/icons-light-mode.svg#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="/static/svg/icons-light-mode.svg#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="/static/svg/icons-light-mode.svg#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>

mailing/templates/mailing/includes/menu.html
<style>

    .sidebar {
        min-height: 100vh; /* Минимальная высота боковой панели */
    }
</style>

<div class="sidebar border border-right col-md-3 col-lg-2 p-0 bg-body-tertiary">
    <div class="offcanvas-md offcanvas-end bg-body-tertiary" tabindex="-1" id="sidebarMenu"
         aria-labelledby="sidebarMenuLabel">
        <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="sidebarMenuLabel">Сервис управления рассылками</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#sidebarMenu"
                    aria-label="Close"></button>
        </div>

        <div class="offcanvas-body d-md-flex flex-column p-0 pt-lg-3 overflow-y-auto">
            <ul class="nav flex-column">

                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2 active" aria-current="page" href="{% url 'mailing:index' %}">
                        <svg class="bi">
                            <use xlink:href="/static/svg/icons-menu.svg#house-fill"/>
                        </svg>
                        Главная
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2" href="{% url 'mailing:recipient_list' %}">
                        <svg class="bi">
                            <use xlink:href="/static/svg/icons-menu.svg#people"/>
                        </svg>
                        Получатели рассылки
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2" href="{% url 'mailing:message_list' %}">
                        <svg class="bi">
                            <use xlink:href="/static/svg/icons-menu.svg#file-earmark-text"/>
                        </svg>
                        Рассылаемые сообщения
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2" href="{% url 'mailing:mailing_list' %}">
                        <svg class="bi">
                            <use xlink:href="/static/svg/icons-menu.svg#play"/>
                        </svg>
                        Управление рассылками
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2" href="{% url 'mailing:mailingattempt_list' %}">
                        <svg class="bi">
                            <use xlink:href="/static/svg/icons-menu.svg#graph-up"/>
                        </svg>
                        Информация о рассылках
                    </a>
                </li>




            <hr class="my-3">
            {% endif %}


            <ul class="nav flex-column mb-auto">

                {% if perms.users.can_block_user %}
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2" href="{% url 'users:users' %}">
                        <svg class="bi">
                            <use xlink:href="/static/svg/icons-menu.svg#people"/>
                        </svg>
                        Пользователи системы
                    </a>
                </li>
                {% endif %}
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <form method="post" action="{% url 'users:logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="nav-link d-flex align-items-center gap-2">
                        <svg class="bi">
                            <use xlink:href="/static/svg/icons-menu.svg#door-closed"/>
                        </svg>
                        Выход
                    </button>
                    </form>
                </li>

                {% else %}

                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2" href="{% url 'users:login' %}">
                        <svg class="bi">
                            <use xlink:href="/static/svg/icons-menu.svg#door-open"/>
                        </svg>
                        Войти
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2" href="{% url 'users:register' %}">
                        <svg class="bi">
                            <use xlink:href="/static/svg/icons-menu.svg#person-plus"/>
                        </svg>
                        Регистрация
                    </a>
                </li>

                {% endif %}

            </ul>

        </div>
    </div>
</div>